name: css_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  google_fonts: ^1.1.0
  keyboard_actions: ^3.3.0+1
  percent_indicator: ^4.0.0
  websafe_svg: ^1.1.4
    # state management, intelligent dependency injection, and route management
  get: ^3.24.0
  # Service lacator
  get_it: ^5.0.4
  # Functional programming thingies
  dartz: ^0.9.2
  # Value equality
  equatable: ^1.2.5
  # Swap the connectivity package for this
  data_connection_checker: ^0.3.4
  # Bloc for state management
  flutter_bloc: ^6.1.1
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  shared_preferences: ^0.5.7+1

  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.3
  cached_network_image: ^2.1.0+1

  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1

  photo_view: ^0.9.2



  fluttertoast: ^7.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/pluto-done.png
     - assets/pluto-fatal-error.png
     - assets/pluto-coming-soon.png
     - assets/pluto-sign-up.png
     - assets/pluto-waiting.png
     - assets/pluto-welcome.png
     - assets/gifs/fade_out_cards.gif
     - assets/gifs/stacked_cards.gif
     - assets/books/
     - assets/authors/
     - images/
     - assets/icons/


  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
